title: Terry Ruas, Ph.D.
author:
  name: Terry Ruas
  email: ruas{at}uni-wuppertal.de

description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal/research page. Here you will find my research interests, publications, short CV, and some other things.
#baseurl: "" # the subpath of your site, e.g. /blog
baseurl: "truas" #github io ues "truas"
#url: "" # the base hostname & protocol for your site, e.g. http://example.com




social_links:
  instagram: terryruas
  github_username:  truas
  twitter: terryruas
  linkedin_username: terryruas

# Build settings
theme: minima

plugins:
- jekyll-feed
- jekyll-seo-tag

minima:
  skin: dark


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
