title: terryruas
author:
  name: Terry Ruas, Ph.D.
  email: ruas{at}uni-wuppertal{dot}de
description: > # this means to ignore newlines until "show_excerpts:"
  Hi, my name is Terry Ruas and I am a Postdoctoral Researcher in the field of Natural Languge Processing (NLP) and Artifical Intelligence (AI). 
other_hobbies:
 I enjoy computers, great food, a good coffee, other things.
footer_notes:
  Here you will find some information about my work, research interests, publications, and teaching. If you have any questions pelase send me an email.

show_excerpts: true # set to true to show excerpts on the homepage

collections:
  authors:
  workexperiences:
  education:

url: http://localhost:4000
baseurl: /truas

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  # generate social links in footer
  social_links:
    twitter: ruasterry
    github: truas
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: terryruas
    linkedin: terryruas
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
